import type { ComponentMeta } from "../../types";

export const meta: ComponentMeta = {
  slug: "platform-downloads",
  name: "Platform Downloads",
  category: "buttons",
  description: "Download and store buttons with the platform marks (macOS, Windows, Linux, App Store, Google Play, Microsoft Store, Android), in separate versions: a smart block that puts the visitor's own system first with the right build chosen, a split menu for the other builds and a copyable install command; or a plain set of badges in solid, outline or light.",
  tags: ["download", "app store", "google play", "macos", "windows", "linux", "badge", "buttons", "platform"],
  traits: ["click", "keyboard", "hover"],
  source: "original",
  files: ["PlatformDownloads.tsx", "platform-downloads.css", "logos.tsx", "platform.ts"],
  dependencies: [],
  prompt:
    "Build download buttons for a desktop and mobile app (a fictional 'Qalam' 2.4.1). Build only the version selected below.\n\nShared badge: an inline 52px link (64px large) with an 11px radius, the platform mark at 27px on the left, and two lines: a small 10.5px top line ('Download for', 'Download on the', 'Get it on', 'Get it from') over an 18px semibold name. Marks are single-colour SVGs in currentColor (Apple, the four-square Windows mark, a penguin, the Android robot head, a shopping bag with four squares) except the Play triangle, which keeps its four colours. Hover lifts 1px, nudges the mark and slides a soft diagonal sheen across once; press moves down 1px. Kinds: macOS, Windows, Linux, Android APK, App Store, Mac App Store, Google Play, Microsoft Store.",
  interaction:
    "Badges are links. The caret opens the build menu (ArrowDown also opens it); ↑/↓, Home and End move, Enter picks, Escape or Tab closes and returns focus. Copy writes the command to the clipboard and announces it. 'Other platforms' is a disclosure.",
  animation: "Hover lift, mark nudge and a one-pass sheen; the menu and the platform list drop in over 0.15s. All removed with reduced motion.",
  a11y: "Real links and buttons; the caret has aria-haspopup, aria-expanded and a label naming the current build; menu rows are menuitemradio with aria-checked. Marks are aria-hidden because the visible text names the platform.",
  responsive: "Badges wrap. Below 520px the split button spans the width and the build line may wrap.",
  touchFallback: "Every control is a tap target; nothing depends on hover.",
  variants: [
    { id: "light", label: "Smart download", prompt: "Smart download block: a 18px-radius card. Heading 'Qalam for macOS' and 'Version 2.4.1 · 2 October 2026'. A large split button: the left part is the download link (mark, 'Download for macOS', and 'Apple silicon · .dmg · 84 MB' under it), the right part a caret that opens a menu of builds as menuitemradio rows (label, a recommended tag on the build matching the detected architecture, format and size). Under it the install command in mono with a $ prompt and a Copy button that turns green 'Copied'. A hairline, then 'Other platforms ▾' revealing transparent hairline-edged badges for the other systems and the stores. On iOS or Android the primary becomes the App Store or Google Play badge; unknown systems see every option. Detection: the user agent plus userAgentData (platform and high-entropy architecture), checking Android before Linux and treating a touch 'Macintosh' as an iPad; it runs after hydration and a detected prop forces it. Light: page #e9e9e6, card #f7f7f5 with a 1px rgb(20 20 20 / 0.11) edge, ink #141414, muted #6c6c69, the split button near-black #0b0b0c with white text, focus and accent #2563eb, copied green #15803d." },
    { id: "dark", label: "Smart download, dark", prompt: "Smart download block: a 18px-radius card. Heading 'Qalam for macOS' and 'Version 2.4.1 · 2 October 2026'. A large split button: the left part is the download link (mark, 'Download for macOS', and 'Apple silicon · .dmg · 84 MB' under it), the right part a caret that opens a menu of builds as menuitemradio rows (label, a recommended tag on the build matching the detected architecture, format and size). Under it the install command in mono with a $ prompt and a Copy button that turns green 'Copied'. A hairline, then 'Other platforms ▾' revealing transparent hairline-edged badges for the other systems and the stores. On iOS or Android the primary becomes the App Store or Google Play badge; unknown systems see every option. Detection: the user agent plus userAgentData (platform and high-entropy architecture), checking Android before Linux and treating a touch 'Macintosh' as an iPad; it runs after hydration and a detected prop forces it. Dark: page #060607, card #101011 with a 1px rgb(255 255 255 / 0.1) edge, ink #f2f2f0, muted #9b9b98, the split button a pale #f4f4f2 slab with #0b0b0c text, focus and accent #7aa2ff, copied green #4ade80." },
    { id: "solid", label: "Solid badges", prompt: "Badge set, solid only: the eight badges grouped under small uppercase 'Desktop' (macOS, Windows, Linux) and 'Stores' (App Store, Google Play, Microsoft Store, Mac App Store, Android APK) labels, then a 'Large' row with the App Store and Google Play badges at 64px, inside a 20px-radius panel (30px by 32px padding, 22px between groups, 10px between badges, wrapping). Solid: near-black #0b0b0c with white text and a 1px #a6a6a6 inner edge, like store badges; hover adds a top highlight and a soft 8px/22px shadow. Panel #f7f7f5 on a #e9e9e6 page, labels #6c6c69. No smart block, no other badge style." },
    { id: "outline", label: "Outline badges", prompt: "Badge set, outline only: the eight badges grouped under small uppercase 'Desktop' (macOS, Windows, Linux) and 'Stores' (App Store, Google Play, Microsoft Store, Mac App Store, Android APK) labels, then a 'Large' row with the App Store and Google Play badges at 64px, inside a 20px-radius panel (30px by 32px padding, 22px between groups, 10px between badges, wrapping). Outline: transparent with a 1.5px rgb(255 255 255 / 0.1) hairline and #f2f2f0 text; hover fills it with #17171a and brightens the hairline. Panel #101011 on a #060607 page, labels #9b9b98. No smart block, no other badge style." },
    { id: "soft-light", label: "Light badges", prompt: "Badge set, light only: the eight badges grouped under small uppercase 'Desktop' (macOS, Windows, Linux) and 'Stores' (App Store, Google Play, Microsoft Store, Mac App Store, Android APK) labels, then a 'Large' row with the App Store and Google Play badges at 64px, inside a 20px-radius panel (30px by 32px padding, 22px between groups, 10px between badges, wrapping). Light: #f4f4f2 with #0b0b0c text, a hairline inner edge and a 1px soft shadow; hover deepens the shadow. Panel #101011 on a #060607 page, labels #9b9b98. No smart block, no other badge style." },
  ],
  preview: { bg: "#e9e9e6", mode: "fill", frame: [1100, 820] },
  isNew: true,
};
