"use client";
import {useState,useId,type ReactNode} from 'react';import {useControllable} from '../../behavior';import './product-atelier.css';
export type AtelierOption={id:string;label:string;values:{id:string;label:string;swatch?:string}[]};
export type AtelierVariant={id:string;selection:Record<string,string>;image:ReactNode;price:number;available:boolean;availability:string};
export type ProductAtelierProps={maker:string;title:string;description:string;options:AtelierOption[];variants:AtelierVariant[];value?:Record<string,string>;onValueChange?:(value:Record<string,string>)=>void;currency?:string;locale?:string;onAdd:(variantId:string)=>Promise<void>|void;surface?:'light'|'dark';className?:string};
export function ProductAtelier({maker,title,description,options,variants,value,onValueChange,currency='USD',locale='en-US',onAdd,surface='light',className=''}:ProductAtelierProps){const uid=useId();const [selection,choose]=useControllable(value,variants[0]?.selection??{},onValueChange);const [state,setState]=useState<'idle'|'pending'|'done'|'error'>('idle');const [error,setError]=useState('');const variant=variants.find(v=>options.every(o=>v.selection[o.id]===selection[o.id]));const fmt=new Intl.NumberFormat(locale,{style:'currency',currency});const digits=fmt.resolvedOptions().maximumFractionDigits??2;
 async function add(){if(!variant?.available||state==='pending')return;setState('pending');try{await onAdd(variant.id);setState('done');}catch(e){setError(e instanceof Error?e.message:'Could not add this item. Please try again.');setState('error');}}
 return <section className={`pat ${className}`} data-surface={surface}><div className="pat__stage" aria-label="Selected product">{variant?.image??<p>Choose an available configuration.</p>}<span className="pat__plate">FORM / 01</span></div><div className="pat__summary"><p className="pat__mono">{maker}</p><h2>{title}</h2><p className="pat__description">{description}</p>{options.map(option=><fieldset key={option.id} disabled={state==='pending'}><legend>{option.label}<span>{option.values.find(v=>v.id===selection[option.id])?.label}</span></legend><div className="pat__choices">{option.values.map(v=><label key={v.id} data-selected={selection[option.id]===v.id}><input type="radio" name={`${uid}-${option.id}`} checked={selection[option.id]===v.id} onChange={()=>{choose({...selection,[option.id]:v.id});setState('idle');}}/>{v.swatch&&<span className="pat__swatch" style={{background:v.swatch}}/>}{v.label}</label>)}</div></fieldset>)}<div className="pat__purchase"><strong>{variant?fmt.format(variant.price/10**digits):'—'}</strong><p aria-live="polite">{variant?.availability??'This combination is not offered.'}</p><button type="button" disabled={!variant?.available||state==='pending'} onClick={add}>{state==='pending'?'Adding…':state==='done'?'Added to basket':'Add to basket'} <span aria-hidden="true">↗</span></button><p className="pat__error" role={state==='error'?'alert':undefined}>{state==='error'?error:''}</p>{state==='done'&&<p role="status">Your chosen configuration is in the basket.</p>}</div></div></section>;
}
