import type { ComponentMeta } from "../../types";

export const meta: ComponentMeta = {
  slug: "status-badge",
  name: "Status Badge",
  category: "feedback",
  description: "Small, quiet status pills for the states a product shows all day: live, online, away, busy, offline, confirmed, pending, cancelled, warning, failed, beta and new. Each has its own mark and word, so colour is never the only signal. Shown as soft, outline, solid and dot looks.",
  tags: ["badge", "status", "pill", "tag", "live", "online", "presence", "confirmed", "pending", "warning", "chip"],
  traits: ["ambient"],
  source: "original",
  files: ["StatusBadge.tsx", "status-badge.css", "status.ts"],
  dependencies: [],
  prompt:
    "Build a status badge (a span) for twelve states in four looks, at two sizes: 24px tall (12.5px Inter 500, 12px mark) and 20px (11.5px, 10px mark), fully rounded, a 6px gap between the mark and the word.\n\nStates, tone and mark: Live (red, a dot with a copy that pings out to 2.4× and fades every 1.6s), Online (green, a solid 7px dot), Away (amber, a crescent), Busy (red, a dot with a short bar cut through it), Offline (grey, a hollow ring), Confirmed (green, a tick), Pending (blue, a 10px spinner, 0.9s a turn), Cancelled (grey, a cross), Warning (amber, a triangle with a stroke and dot), Failed (red, a cross), Beta (violet, a four-point spark), New (blue, the spark). The word can be overridden ('Processing' for pending).\n\nTones (light / dark), strong ink then tint then hairline: red #c4161c #fdecec #f6c1c2 / #ff8a8d #2c1214 #5a2226; green #13703a #e7f6ec #b6e2c4 / #6fdc93 #0f2416 #1f4a2c; amber #935f00 #fdf3dc #f1d697 / #f8c45c #2a1f08 #574117; grey #5c5f66 #f0f1f3 #d9dbe0 / #b3b6bd #1d1e21 #34363b; blue #1d4fd8 #e9f0ff #bfd0fb / #8db3ff #0f1b33 #23396a; violet #6b2fd6 #f2ecff #d6c5fa / #c4a6ff #1d1430 #3d2b66. All pass 4.5:1 for the word on its fill.\n\nLooks: soft is the tint with a 1px inset hairline in the tone and the word and mark in the strong ink; outline is a transparent pill with only the hairline; solid is the saturated tone (red #dc2626 / #e5484d, green #15803d / #238636, amber #f5a524, grey #5c5f66 / #4a4d54, blue #2563eb / #2f6bff, violet #7c3aed / #7c4dff) with white text, except amber, which takes near-black #241700; dot has no pill, just the mark in the tone and the word in plain body text (13.5px, 400) as in a presence list.\n\nShow a section per look with all twelve statuses, then a short order list (name, time, a small soft badge) on a white / #0b0b0c page.",
  interaction: "None; badges are labels. Put them next to the thing they describe.",
  animation: "Only Live pings and Pending spins; reduced motion stops the ping and slows the spinner.",
  a11y: "The word is real text and the mark is aria-hidden, so the state reads the same without colour. If a status changes live, wrap it in a polite live region.",
  responsive: "Badges wrap in rows and never wrap their own text.",
  touchFallback: "Nothing to tap.",
  variants: [
    { id: "light", label: "Light", prompt: "Palette for this theme (Light): --stbg-amber #935f00; --stbg-amber-line #f1d697; --stbg-amber-soft #fdf3dc; --stbg-blue #1d4fd8; --stbg-blue-line #bfd0fb; --stbg-blue-soft #e9f0ff; --stbg-blue-solid #2563eb; --stbg-green #13703a; --stbg-green-line #b6e2c4; --stbg-green-soft #e7f6ec; --stbg-green-solid #15803d; --stbg-grey #5c5f66; --stbg-grey-line #d9dbe0; --stbg-grey-soft #f0f1f3; --stbg-grey-solid #5c5f66; --stbg-red #c4161c; --stbg-red-line #f6c1c2; --stbg-red-soft #fdecec; --stbg-red-solid #dc2626; --stbg-text #1d1e21; --stbg-violet #6b2fd6; --stbg-violet-line #d6c5fa; --stbg-violet-soft #f2ecff; --stbg-violet-solid #7c3aed. Treat these as the root colour tokens, one value per role, and name them to suit your code. Select it with the theme option set to \"light\". Keep every dimension, spacing value, state and motion from the brief unchanged, and keep text at 4.5:1 contrast or better on these surfaces." },
    { id: "dark", label: "Dark", prompt: "Palette for this theme (Dark): --stbg-amber #f8c45c; --stbg-amber-line #574117; --stbg-amber-soft #2a1f08; --stbg-blue #8db3ff; --stbg-blue-line #23396a; --stbg-blue-soft #0f1b33; --stbg-blue-solid #2f6bff; --stbg-green #6fdc93; --stbg-green-line #1f4a2c; --stbg-green-soft #0f2416; --stbg-green-solid #238636; --stbg-grey #b3b6bd; --stbg-grey-line #34363b; --stbg-grey-soft #1d1e21; --stbg-grey-solid #4a4d54; --stbg-red #ff8a8d; --stbg-red-line #5a2226; --stbg-red-soft #2c1214; --stbg-red-solid #e5484d; --stbg-text #e8e9ec; --stbg-violet #c4a6ff; --stbg-violet-line #3d2b66; --stbg-violet-soft #1d1430; --stbg-violet-solid #7c4dff. Treat these as the root colour tokens, one value per role, and name them to suit your code. Select it with the theme option set to \"dark\". Keep every dimension, spacing value, state and motion from the brief unchanged, and keep text at 4.5:1 contrast or better on these surfaces." },
  ],
  preview: { bg: "#ffffff", mode: "fill", frame: [1000, 820] },
};
