import type { ComponentMeta } from "../../types";

export const meta: ComponentMeta = {
  slug: "split-brief-composer",
  name: "Split-Brief Composer",
  category: "ai",
  description: "A mission briefing for an agent in two surfaces: what should happen on the left, how the agent should do it on the right. The right side reads the left as you write and marks what it would suggest — a mode, the files you named, more effort for careful work, a model — but nothing changes until you accept it.",
  tags: ["ai", "agent", "composer", "split view", "suggestions", "briefing", "model", "mode", "effort", "files"],
  traits: ["click", "keyboard", "touch"],
  source: "original",
  isNew: true,
  files: ["SplitBriefComposer.tsx", "split-brief-composer.css", "infer.ts", "brief.ts", "logos.tsx"],
  dependencies: [],
  prompt:
    "Build a composer for a coding agent as two surfaces in one 62rem card (18px radius): on the left 'WHAT SHOULD HAPPEN?' and on the right 'HOW SHOULD THE AGENT DO IT?', with small mono caps headings. The left is the card's surface and holds a large borderless prompt (19px/30px, at least 300px tall) and a footer under a dashed rule: a word count (or 'Plain words are fine — the right side reads them.'), ⌘ ↵ key hints and a round send button. The right is a slightly different surface with a hairline between them.\n\nThe right side has four groups, each with a mono caps legend: MODE as pills with the mode's line icon (Agent, Plan, Debug, Multitask, Ask); MODEL as pills with the maker's logo (Claude's orange, OpenAI's blue, Grok's white on a black disc); EFFORT as five steps whose bars rise from 8px to 24px and fill up to the chosen level in the level's colour (Low grey, Medium green, High amber, Extra High violet, Max red); CONTEXT as a list of files with checkboxes, token counts, and in the legend the total and the share of the chosen model's window. A selected pill gets a 13% tint and a 1.5px ring in its own colour.\n\nThe right side reads the left a beat after typing stops, using plain keyword rules (timeout or error → Debug; plan or migrate → Plan; a question → Ask; several lines → Multitask; carefully or production → more effort; named things → files), but it only suggests: a blue '• suggested' tag appears on the pill it would choose, a dashed blue outline on the effort step it would raise to, an italic reason under the group ('Suggested Debug: you wrote “time out”.'), and files you named float to the top with a blue outline and 'mentioned · add'. A blue 'Apply 3 suggestions' button in the header takes them all at once. Nothing is ever changed for you.\n\nBelow 720px of its own width the two stack: the prompt on top, and the right side collapses into a drawer row 'HOW  Agent · Astra · Medium · 0 files ⌄' with a blue count of suggestions; tapping it opens the groups beneath.",
  interaction:
    "Write on the left. On the right, pick a mode, model, effort and files, or accept what it suggests — one at a time by choosing the tagged option, or all at once with Apply. ⌘/Ctrl+Enter sends. On narrow screens the right side is a drawer you open from its summary row.",
  animation: "Suggestion tags and the Apply button fade in, the tag's dot pings twice, effort bars fill to the new level, the drawer chevron turns; reduced motion makes every change instant.",
  a11y: "Two labelled regions; mode, model and effort are radio groups, files are checkboxes, each option names itself and describes what it does; suggestions are visible text inside the option they apply to; the drawer toggle has aria-expanded; changes are announced politely.",
  responsive: "Below 720px of its own width the surfaces stack, the right side becomes a drawer with a summary and suggestion count, and targets grow to 38–40px.",
  touchFallback: "Every option is a tap target; nothing depends on hover.",
  variants: [
    { id: "dark", label: "Dark", prompt: "Palette for this theme (Dark): --spbf-agent #d4d4d4; --spbf-ask #8fd18a; --spbf-card #161616; --spbf-claude #e08560; --spbf-debug #f08c7b; --spbf-e0 #8e8e8e; --spbf-e1 #6cc08b; --spbf-e2 #e6c26b; --spbf-e3 #b48cf2; --spbf-e4 #f0645a; --spbf-faint #5a5a5a; --spbf-focus #8ab4f8; --spbf-go #ededed; --spbf-go-ink #111111; --spbf-hover rgb(255 255 255 / 0.05); --spbf-ink #ececec; --spbf-line #2a2a2a; --spbf-line-soft rgb(255 255 255 / 0.06); --spbf-multitask #7cc5ee; --spbf-muted #8c8c8c; --spbf-off #353535; --spbf-openai #5b9bff; --spbf-opt #222222; --spbf-plan #e6c26b; --spbf-side #1b1b1b; --spbf-sug #8ab4f8; --spbf-xai #ffffff. Treat these as the root colour tokens, one value per role, and name them to suit your code. Select it with the theme option set to \"dark\". Keep every dimension, spacing value, state and motion from the brief unchanged, and keep text at 4.5:1 contrast or better on these surfaces." },
    { id: "light", label: "Light", prompt: "Palette for this theme (Light): --spbf-agent #3b3b3b; --spbf-ask #2e8538; --spbf-card #ffffff; --spbf-claude #c25a32; --spbf-debug #b5432e; --spbf-e0 #7a7a7a; --spbf-e1 #2f8f55; --spbf-e2 #a8730a; --spbf-e3 #7d4fd1; --spbf-e4 #cc3a30; --spbf-faint #a6a6a6; --spbf-focus #2b59c3; --spbf-go #1b1b1b; --spbf-go-ink #ffffff; --spbf-hover rgb(0 0 0 / 0.04); --spbf-ink #181818; --spbf-line #e2e2e0; --spbf-line-soft rgb(0 0 0 / 0.06); --spbf-multitask #1d74a6; --spbf-muted #6b6b6b; --spbf-off #dcdcdc; --spbf-openai #2563d6; --spbf-opt #ffffff; --spbf-plan #96650a; --spbf-side #f7f7f6; --spbf-sug #2b59c3; --spbf-xai #0b0b0b. Treat these as the root colour tokens, one value per role, and name them to suit your code. Select it with the theme option set to \"light\". Keep every dimension, spacing value, state and motion from the brief unchanged, and keep text at 4.5:1 contrast or better on these surfaces." },
  ],
  preview: { bg: "#0a0a0a", mode: "fill", frame: [1280, 820] },
};
